# Generated by Django 3.0.3 on 2020-03-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Марка машины')),
                ('model', models.CharField(max_length=100, verbose_name='Модель машины')),
                ('img', models.ImageField(blank=True, upload_to='images/', verbose_name='Изображение')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('offer', models.BooleanField(default=False)),
                ('public_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('year', models.IntegerField(verbose_name='Год выпуска')),
            ],
        ),
    ]
