# Generated by Django 3.0.3 on 2020-03-24 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0002_auto_20200320_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterField(
            model_name='car',
            name='img',
            field=models.ImageField(blank=True, upload_to='img', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('comment_text', models.TextField(verbose_name='Текст комментария')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carApp.Car')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
