# Generated by Django 3.0.3 on 2020-03-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ava',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='Фото'),
        ),
    ]
