# Generated by Django 3.0.3 on 2020-03-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0006_auto_20200331_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default='', verbose_name='URL'),
        ),
    ]
