# Generated by Django 3.0.3 on 2020-04-01 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0007_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
