# Generated by Django 3.0.3 on 2020-04-03 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carApp', '0008_auto_20200401_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='desc_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='car',
            name='desc_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Модель машины'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Модель машины'),
        ),
        migrations.AddField(
            model_name='car',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Марка машины'),
        ),
        migrations.AddField(
            model_name='car',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Марка машины'),
        ),
    ]
